server:
  port: 8082

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/littlebee

logging:
  level:
    root: INFO
    org.springframework.security: INFO